frontside/src/main/java/stingion/ijuke/frontside/web/action/ContactFormActionBean.java
/**
 * Created under not commercial project "ijuke"
 */

package stingion.ijuke.frontside.web.action;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.DontValidate;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.SimpleMessage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import net.sourceforge.stripes.validation.SimpleError;
import net.sourceforge.stripes.validation.ValidationErrors;
import net.sourceforge.stripes.validation.ValidationMethod;
import stingion.ijuke.utils.ijuke.dto.ContactDTO;
import stingion.ijuke.utils.ijuke.modeltypes.Gender;

public class ContactFormActionBean extends ContactBaseActionBean {

    @SpringBean("contact_form.jsp")
    private String form;

    @DefaultHandler
    public Resolution form() {
        return new ForwardResolution(form);
    }

    @ValidationMethod(on = "save")
    public void validateEmailUnique(ValidationErrors errors) {
        String email = getContact().getEmail();
        ContactDTO other = getContactService().getContactByEmail(email);
        if (other != null && !other.equals(getContact())) {
            errors.add("contact.email", new SimpleError("{1} is already used by {2}.", other));
        }
    }

    public Resolution save() {
        ContactDTO contact = getContact();

        String saveOrUpdateWord = contact.getId() == null ? "create" : "update";

        if ("create".equals(saveOrUpdateWord))
            getContactService().create(contact);
        else
            getContactService().update(contact);

        getContext().getMessages().add(new SimpleMessage("{0} has been " + saveOrUpdateWord + "d" + ".", contact));
        return new RedirectResolution(ContactListActionBean.class);
    }

    @DontValidate
    public Resolution cancel() {
        getContext().getMessages().add(new SimpleMessage("Action cancelled."));
        return new RedirectResolution(ContactListActionBean.class);
    }

    public Gender[] getGenders() {
        return Gender.values();
    }
}

frontside/src/main/java/stingion/ijuke/frontside/web/action/ContactListActionBean.java
package stingion.ijuke.frontside.web.action;

import net.sourceforge.stripes.action.DefaultHandler;
import net.sourceforge.stripes.action.ForwardResolution;
import net.sourceforge.stripes.action.RedirectResolution;
import net.sourceforge.stripes.action.Resolution;
import net.sourceforge.stripes.action.SimpleMessage;
import net.sourceforge.stripes.integration.spring.SpringBean;
import stingion.ijuke.utils.ijuke.dto.ContactDTO;

import java.util.List;

public class ContactListActionBean extends ContactBaseActionBean {

    @SpringBean("contact_list.jsp")
    private String contactList;

    @SpringBean("contact_view.jsp")
    private String contactView;

    public Resolution view() {
        return new ForwardResolution(contactView);
    }

    public Resolution delete() {
        ContactDTO deleted = getContact();
        contactService.delete(deleted);
        getContext().getMessages().add(new SimpleMessage("Deleted {0}.", deleted));
        return new RedirectResolution(getClass());
    }

    @DefaultHandler
    public Resolution list() {
        return new ForwardResolution(contactList);
    }

    public List<ContactDTO> getContacts() {
        return contactService.getAll();
    }
}

frontside/src/main/webapp/WEB-INF/jsp/contact_form.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_menu.jsp" title="Contact Information" currentSection="CONTACT_LIST">
    <s:layout-component name="body">

        <s:form beanclass="stingion.ijuke.frontside.web.action.ContactFormActionBean">

            <s:errors/>

            <div><s:hidden name="contact.id"/></div>
            <table class="form">
                <tr>
                    <td><s:label for="contact.firstName"/>:</td>
                    <td><s:text name="contact.firstName"/></td>
                </tr>
                <tr>
                    <td><s:label for="contact.middleName"/>:</td>
                    <td><s:text name="contact.middleName"/></td>
                </tr>
                <tr>
                    <td><s:label for="contact.lastName"/>:</td>
                    <td><s:text name="contact.lastName"/></td>
                </tr>
                <tr>
                    <td><s:label for="contact.email"/>:</td>
                    <td><s:text name="contact.email"/></td>
                </tr>

                <tr>
                    <td><s:label for="contact.phoneNumber"/>:</td>
                    <td><s:text name="contact.phoneNumber" formatType="phoneNumber.parens"/></td>
                </tr>
                <tr>
                    <td><s:label for="contact.birthDay"/>:</td>
                    <td><s:text name="contact.birthDay" formatPattern="dd/MM/yyyy"/></td>
                </tr>
                <tr>
                    <td><s:label for="contact.gender"/>:</td>
                    <td class="field">
                        <c:forEach var="gender" items="${actionBean.genders}">
                            <s:radio name="contact.gender" value="${gender}"/>${gender}
                        </c:forEach>
                    </td>
                </tr>
                <tr>
                    <td>&nbsp;</td>
                    <td>
                        <s:submit name="save" value="Save"/>
                        <s:submit name="cancel" value="Cancel"/>
                    </td>
                </tr>
            </table>
        </s:form>

    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/contact_list.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_menu.jsp" title="Contact List" currentSection="CONTACT_LIST">
    <s:layout-component name="body">

        <s:link beanclass="stingion.ijuke.frontside.web.action.ContactFormActionBean">
            Create a New Contact
        </s:link>

        <d:table name="${actionBean.contacts}" id="contact" requestURI="" defaultsort="1" summary="Contact List Table">
            <d:column title="First name"  property="firstName"  sortable="true"/>
            <d:column title="Middle name" property="middleName" sortable="true"/>
            <d:column title="Last name"   property="lastName"   sortable="true"/>
            <d:column title="Email"       property="email"      sortable="true"/>
            <d:column title="Action">
                <s:link beanclass="stingion.ijuke.frontside.web.action.ContactListActionBean" event="view">
                    <s:param name="contactId" value="${contact.id}"/>
                    View
                </s:link> |
                <s:link beanclass="stingion.ijuke.frontside.web.action.ContactFormActionBean">
                    <s:param name="contactId" value="${contact.id}"/>
                    Update
                </s:link> |
                <s:link beanclass="stingion.ijuke.frontside.web.action.ContactListActionBean" event="delete"
                        onclick="return confirm('Delete ${contact}?');">
                    <s:param name="contactId" value="${contact.id}"/>
                    Delete
                </s:link>
            </d:column>
        </d:table>

    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/contact_view.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>

<s:layout-render name="/WEB-INF/jsp/common/layout_menu.jsp" title="Contact Information" currentSection="CONTACT_LIST">
    <s:layout-component name="body">
        <table class="view">
            <tr>
                <td class="label"><s:label for="contact.firstName"/>:</td>
                <td class="value">${actionBean.contact.firstName}</td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.middleName"/>:</td>
                <td class="value">${actionBean.contact.middleName}</td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.lastName"/>:</td>
                <td class="value">${actionBean.contact.lastName}</td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.email"/>:</td>
                <td class="value">${actionBean.contact.email}</td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.phoneNumber"/>:</td>
                <td class="value"><s:format value="${actionBean.contact.phoneNumber}"
                                            formatType="phoneNumber.parens"/></td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.birthDay"/>:</td>
                <td class="value">
                    <s:format value="${actionBean.contact.birthDay}" formatPattern="dd/MM/yyyy"/>
                </td>
            </tr>
            <tr>
                <td class="label"><s:label for="contact.gender"/>:</td>
                <td class="value">${actionBean.contact.gender}</td>
            </tr>
        </table>
        <p>
            <s:link beanclass="stingion.ijuke.frontside.web.action.ContactFormActionBean">
                <s:param name="contactId" value="${actionBean.contact.id}"/>
                Update
            </s:link> |
            <s:link beanclass="stingion.ijuke.frontside.web.action.ContactListActionBean">
                Back to List
            </s:link>
        </p>
    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/message_compose.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_menu.jsp"  title="Message Compose" currentSection="COMPOSE">
    <s:layout-component name="body">
        Message Compose goes here
    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/message_details.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_folders.jsp" title="Message Details" currentSection="MESSAGE_LIST">
    <s:layout-component name="body">
        Message details go here
    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/message_list.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp"%>

<s:layout-render name="/WEB-INF/jsp/common/layout_folders.jsp" title="Message List" currentSection="MESSAGE_LIST">
    <s:layout-component name="body">
        Message list goes here

        <br/>
        <s:link beanclass="stingion.ijuke.frontside.web.action.MessageDetailsActionBean">
            Message details
        </s:link>

    </s:layout-component>
</s:layout-render>

frontside/src/main/webapp/WEB-INF/jsp/view_source.jsp
<%@include file="/WEB-INF/jsp/common/taglibs.jsp" %>
<%@taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<!DOCTYPE log4j:configuration PUBLIC "-//LOGGER"
"http://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/xml/doc-files/log4j.dtd">

<html>
    <head>
        <title>View source - ${actionBean.filename}</title>
        <link rel="shortcut icon" href="${contextPath}/images/ijuke.png" type="image/x-icon">
    </head>
    <body>
        <p><u>View source - ${actionBean.filename}</u></p>
        <pre>${fn:escapeXml(actionBean.source)}</pre>
    </body>
</html>